version: '3.4'

services:
    # Microservice 1 - User
    userservicedb:
        image: mongo

    user.api:
        # image: ${DOCKER_REGISTRY-}userapi
        image: phalder/userapi
        build:
            context: .
            dockerfile: Source/UserService/User.API/Dockerfile

    # Microservice 2 - Alert
    alertservicedb:
        image: redis

    alerts.api:
        image: phalder/alertsapi
        build:
            context: .
            dockerfile: Source/AlertService/Alert.API/Dockerfile

