apiVersion: apps/v1
kind: Deployment
metadata:
    name: userapi-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: userapi
    template:
        metadata:
            labels:
                app: userapi
        spec:
            containers:
                - name: userapi
                  image: phalder/userapi
                  env:
                  - name: "ASPNETCORE_ENVIRONMENT"
                    value: "Development"
                  - name: UserDBSettings__ConnectionString
                    value: "mongodb://userservicedb:27017"
---
apiVersion: v1
kind: Service
metadata:
    name: userapi-service
spec:
    type: NodePort
    selector:
        app: userapi
    ports:
        - name: userapi
          protocol: TCP    
          port: 8000
          # From Docker Override file
          targetPort: 80
            # Optional field
            # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
          nodePort: 30007